string header
string sender
string receiver
float32[] sender_psi_u
float32[] receiver_psi_u
int32 msg_id
---
string header
string sender
string receiver
float32[] sender_psi_u
float32[] receiver_psi_u
int32 msg_id
